apiVersion: v1
kind: Namespace
metadata: 
  name: demo
  labels: 
      name: demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato
  template:
    metadata:
      labels:
        app: podtato
    spec:
      containers:
        - name: podtato
          image: podtato:latest
          # forces use of local image 
          imagePullPolicy: Never 
    

---

apiVersion: v1
kind: Service
metadata:
  name: podtato
  namespace: demo
spec:
  selector:
    app: podtato
  ports:
  - name: endpoint
    port: 8080
    targetPort: 8080


