apiVersion: v1
kind: Namespace
metadata: 
  name: demo
  labels: 
      name: demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato
  template:
    metadata:
      labels:
        app: podtato
    spec:
      containers:
        - name: podtato
          image: podtato-debug:0.0.1  
          imagePullPolicy: Never 
          env:
          - name: "PORT"
            value: "8080"
          volumeMounts:
          - mountPath: /go/src
            name: source-code
      volumes:
      - name: source-code
        hostPath:
          path: /home/jam/go/src
          type: Directory    

---

apiVersion: v1
kind: Service
metadata:
  name: podtato
  namespace: demo
spec:
  selector:
    app: podtato
  ports:
  - name: endpoint
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: debug
  namespace: demo
spec:
  selector:
    app: podtato
  ports:
  - name: debug
    port: 30123
    targetPort: 30123
